### ISSUE TITLE
ios 微信  6.6.7版本

### ISSUE THREAD

**Issue by liaoyinglong** [vincheung/back#1]
ios微信 6.6.7的版本内置浏览器更新了之后，页面下方多了一个工具条，有了前进后退键。

点击后退并不会关闭浏览器。

有解决方法吗？

**Comment by karl-cheung** [comment]
你好，收到你的反馈我测试了这个版本，并没有上述问题。你可以发送一个简易版的demo或者链接至我的邮箱，我会仔细甄别问题所在。另外这个库的引入规则是，在所需退出应用的页面引入。

**Comment by liaoyinglong** [comment]
不好意思，浪费你的时间了。

经过排查是其他原因，是我的问题。

谢谢你！
